apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 26.0.0
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:      # Isto ativa a sincronização automática
      prune: true   # Apaga recursos no cluster se os apagares no Git
      selfHeal: true # Se mudares algo manualmente no cluster, o Argo corrige
    createNamespace: true
